### ISSUE TITLE
The code cannot run

### ISSUE THREAD

**Issue by Ljw3336699** [thuml/Time-Series-Library#437]
Follow the markdown,pip install -r requirements.txt
it appears  cannot import name 'einsum' from 'einops'
after upgrade einops to 0.8.0
it still cannot run, it shows no kernel image is available for execution on the device

**Comment by wuhaixu2016** [comment]
@sky-wu-ying Thanks for your answer.
